apiVersion: v1
data:
  .env: |-
    key1=value1
    env=qa
kind: ConfigMap
metadata:
  name: configFromFile-456kgtfd6m
---
apiVersion: v1
data:
  Key1: value1
  Key2: value2
kind: ConfigMap
metadata:
  name: configFromLiterals-h777b4gdf5
---
apiVersion: v1
data:
  env: qa
  key1: value1
kind: ConfigMap
metadata:
  name: configMapFromEnv-c9655hf97k
