apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefix-codeWizard-myapp-suffix-codeWizard
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: __image__
        name: myapp
